config/routes.rb
Rails.application.routes.draw do
  resources :wadgets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :first, presence: true
  validates :last, presence: true
  validates :email, presence: true
end

app/models/wadget.rb
class Wadget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wadgets_controller.rb
class WadgetsController < ApplicationController
  before_action :set_wadget, only: [:show, :edit, :update, :destroy]

  # GET /wadgets
  # GET /wadgets.json
  def index
    @wadgets = Wadget.all
    WebNotificationsChannel.broadcast_to('web_notifications_channel', title: 'New things!', body: 'All the news fit to print')
  end

  # GET /wadgets/1
  # GET /wadgets/1.json
  def show
  end

  # GET /wadgets/new
  def new
    @wadget = Wadget.new
  end

  # GET /wadgets/1/edit
  def edit
  end

  # POST /wadgets
  # POST /wadgets.json
  def create
    @wadget = Wadget.new(wadget_params)

    respond_to do |format|
      if @wadget.save
        format.html { redirect_to @wadget, notice: 'Wadget was successfully created.' }
        format.json { render :show, status: :created, location: @wadget }
      else
        format.html { render :new }
        format.json { render json: @wadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wadgets/1
  # PATCH/PUT /wadgets/1.json
  def update
    respond_to do |format|
      if @wadget.update(wadget_params)
        format.html { redirect_to @wadget, notice: 'Wadget was successfully updated.' }
        format.json { render :show, status: :ok, location: @wadget }
      else
        format.html { render :edit }
        format.json { render json: @wadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wadgets/1
  # DELETE /wadgets/1.json
  def destroy
    @wadget.destroy
    respond_to do |format|
      format.html { redirect_to wadgets_url, notice: 'Wadget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wadget
      @wadget = Wadget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wadget_params
      params.require(:wadget).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wadgets_helper.rb
module WadgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wadgets/_form.html.erb
<%= form_with(model: wadget, local: true) do |form| %>
  <% if wadget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wadget.errors.count, "error") %> prohibited this wadget from being saved:</h2>

      <ul>
        <% wadget.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wadgets/edit.html.erb
<h1>Editing Wadget</h1>

<%= render 'form', wadget: @wadget %>

<%= link_to 'Show', @wadget %> |
<%= link_to 'Back', wadgets_path %>

app/views/wadgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wadgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wadgets.each do |wadget| %>
      <tr>
        <td><%= wadget.name %></td>
        <td><%= link_to 'Show', wadget %></td>
        <td><%= link_to 'Edit', edit_wadget_path(wadget) %></td>
        <td><%= link_to 'Destroy', wadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wadget', new_wadget_path %>

app/views/wadgets/new.html.erb
<h1>New Wadget</h1>

<%= render 'form', wadget: @wadget %>

<%= link_to 'Back', wadgets_path %>

app/views/wadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wadget.name %>
</p>

<%= link_to 'Edit', edit_wadget_path(@wadget) %> |
<%= link_to 'Back', wadgets_path %>